### ISSUE TITLE
In 64bit system the path /usr/local/lib/ , change to /usr/local/lib64/

### ISSUE THREAD

**Issue by wjn740** [yoshizow/global-pygments-plugin#6]
Sir, 

In 64bit system, I found I have to change the path.

Tested OS: OpenSUSE Leap 42.1 64Bit

**Comment by yoshizow** [comment]
Thank you for your report.
Could you tell me how did you install GLOBAL?

1) zypper install global
or
2) download global-6.5.2.tar.gz
    ./configure
    make ; make install
or
3) other

In case of 2, which option did you specify to configure? which version of GLOBAL?

**Comment by wjn740** [comment]
zypper in global.

**Comment by yoshizow** [comment]
This issue seems to have been fixed in GLOBAL-6.5.2.
Since GLOBAL-6.5.2, library paths in gtags.conf is generated based on configure's libdir variable instead of hard-coded /lib/ paths.
http://lists.gnu.org/archive/html/info-global/2015-12/msg00000.html

**Comment by wjn740** [comment]
OK,

It means that this is a problem to openSUSE?

**Comment by yoshizow** [comment]
> It means that this is a problem to openSUSE?

Yes. Currently OpenSUSE's \`global\` package is built with GLOBAL version 6.5.1.
The package maintainer should update \`global\` package with latest version of GLOBAL.

```
$ zypper info global
Information for package global:
-------------------------------
Repository: OSS
Name: global
Version: 6.5.1-1.3
Arch: x86_64
Vendor: openSUSE
```

**Comment by wjn740** [comment]
OK, I will try to tell maintainer what should he do.
